system:
  host: 0.0.0.0
  port: 8009
  LogLevel: all
  appName: floodproxy
  startby: 0
httpProxy:
  - target: target1
    proxypass: http://10.201.2.32:8080
  - target: target2
    proxypass: http://10.201.2.32:8080