system:
  host: 0.0.0.0
  port: 8009
  LogLevel: all
  appName: floodproxy
httpProxy:
  - target: target1
    proxypass: http://127.0.0.1:54436
  - target: target2
    proxypass: http://127.0.0.1:54436