system:
  host: 0.0.0.0
  port: 8009
  LogLevel: all
  appName: floodproxy
httpProxy:
  - target: target1
    proxypass: http://172.16.5.132:8006
  - target: target2
    proxypass: http://172.16.5.132:8006